# Jekyll Resume Theme

# Site settings
title: Nathan Schepers
email: nathan.schepers@protonmail.com
description: Nathan Schepers - Resume
url: "https://nathanschepers.ca/"
name: Nathan Schepers
location: Granada, Spain (CET/CEST)
email_address: nathan.schepers@protonmail.com

# Build settings
markdown: kramdown
