# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: build-and-deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: '2.7'
      - name: Install wkhtmltopdf
        run: |
          sudo apt-get install wkhtmltopdf
      - name: Build
        run: |
          chmod +x ./bin/build.sh
          ./bin/build.sh
      - name: List files in the staging dir
        run: |
          ls ${{ github.workspace }}/stage/